### ISSUE TITLE
Mac OS Sierra Support

### ISSUE THREAD

**Issue by ghost** [AntonioMeireles/coreos-xhyve#86]
I realize Sierra is beta is probably not yet on the road map, but just so you know:
When attempting to install with brew on Sierra, XCode 8 Beta3, I get:

==> Downloading https://github.com/TheNewNormal/corectl/archive/v0.7.13.tar.gz
Already downloaded: /Users/ian/Library/Caches/Homebrew/corectl-0.7.13.tar.gz
==> opam init --no-setup
==> opam pin add qcow-format https://github.com/mirage/ocaml-qcow.git#96db516d97b1c3ef2c7bccdac8fb6cfdcb667a04
==> opam install uri qcow-format ocamlfind
==> make tarball VERSION=0.7.13
Last 15 lines from /Users/ian/Library/Logs/Homebrew/corectl/04.make:
        ^
src/vmm/vmm.c:95:24: note: expanded from macro 'vcpu_unlock'
# define vcpu_unlock(v) OSSpinLockUnlock(&(v)->lock)

```
                   ^
```

In file included from src/vmm/vmm.c:36:
In file included from /usr/include/libkern/OSAtomic.h:44:
/usr/include/libkern/OSSpinLockDeprecated.h:105:9: note: 'OSSpinLockUnlock' has been explicitly marked deprecated here
void    OSSpinLockUnlock( volatile OSSpinLock ___lock );
        ^
19 errors generated.
make[1]: *_\* [build/vmm/vmm.o] Error 1
make[1]: **\* Waiting for unfinished jobs....
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml/compiler-libs, /usr/local/lib/ocaml
make: **\* [hyperkit] Error 2
make: **\* Waiting for unfinished jobs....

**Comment by AntonioMeireles** [comment]
Hey, 

at sight that's exclusively an upstream issue on the toolchain of one of the components we use under the skin - hyperkit (docker's take on xhyve) . Once they get it Sierra ready (and they will as that is one of  the core parts of docker for mac) we'll get it for free :-) no point for us to to waste resources on fix this now as they have a so well oiled maintainer... so i expect this to get solved soonish :-)

**Comment by rimusz** [comment]
I have tested the built one v0.7.14 from releases on latest Siera beta 3, it did run at no problem there.
So must be the building fails on Siera

**Comment by ghost** [comment]
Hi Rimas
Just to be sure: are you using XCode 8 beta3?
I still have the same issue:

==> opam init --no-setup
==> opam pin add qcow-format https://github.com/mirage/ocaml-qcow.git#96db516d97b1c3ef2c7bccdac8fb6cfdcb667a04
==> opam install uri qcow-format ocamlfind
==> make tarball VERSION=0.7.14
Last 15 lines from /Users/ian/Library/Logs/Homebrew/corectl/04.make:
#define vcpu_unlock(v) OSSpinLockUnlock(&(v)->lock)
                       ^
In file included from src/vmm/vmm.c:36:
In file included from /usr/include/libkern/OSAtomic.h:44:
/usr/include/libkern/OSSpinLockDeprecated.h:105:9: note: 'OSSpinLockUnlock' has been explicitly marked deprecated here
void    OSSpinLockUnlock( volatile OSSpinLock ___lock );
        ^
19 errors generated.
cc src/vmm/vmm_instruction_emul.c
cc src/vmm/vmm_ioport.c
make[1]: *_\* [build/vmm/vmm.o] Error 1
make[1]: **\* Waiting for unfinished jobs....
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml/compiler-libs, /usr/local/lib/ocaml
make: **\* [hyperkit] Error 2
make: **\* Waiting for unfinished jobs...

Ian de Beer

zenAptix (Pty) Ltd
Octo Place Block B, Unit B01,
Electron Rd,
Technopark.
Stellenbosch, 
South Africa

Mobile: +27 82 887 0926
web: http://www.zenaptix.com

This e-mail transmission contains confidential information, which is the property of EOH Holdings Limited and its subsidiaries (“EOH”). No person, other than the recipient (so indicated by the sender) may use or disclose the contents of this message, links or attachments hereto, to any person whatsoever. Unauthorised disclosure and/or use may result in civil and criminal liability.

Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorised to state them to be the views of any such entity.

The disclaimer forms part of the content of this e-mail in terms of section 11 of the Electronic Communications and Transactions Act, 25 of 2002. Refer to http://www.eoh.co.za/disclaimer

**Comment by AntonioMeireles** [comment]
@zenaptix 

Hi! 

hyperkit _still_ doesn't build correctly in 10.12  (see among others) [this](https://github.com/docker/hyperkit/pull/49) upstream bug. a cheap trick is to build all else (the golang based bits) under 10.12 and re-use the 10.11 hyperkit (correctly.runner) blob (which afaict is what @rimusz was actually doing :-) )

**Comment by AntonioMeireles** [comment]
@zenaptix could you try plz try to build latest head under 10.12 and report how far you can go now ?

Thanks in advance

**Comment by ghost** [comment]
Hi Antonio
Just to be clear - I am using brew to do the install - the latest release is still 0.7.14. I am not to sure how to do a manual build.
The problem is still there though (using brew install corectl)
Regards
Ian

Already downloaded: /Users/ian/Library/Caches/Homebrew/corectl-0.7.14.tar.gz
==> opam init --no-setup
==> opam pin add qcow-format https://github.com/mirage/ocaml-qcow.git#96db516d97b1c3ef2c7bccdac8fb6cfdcb667a04
==> opam install uri qcow-format ocamlfind
==> make tarball VERSION=0.7.14
Last 15 lines from /Users/ian/Library/Logs/Homebrew/corectl/04.make:
In file included from src/vmm/intel/vmx.c:50:
include/xhyve/vmm/io/vlapic_priv.h:166:2: error: 'OSSpinLock' is deprecated: first deprecated in OS X 10.12 - Use os_unfair_lock() from <os/lock.h>
      instead [-Werror,-Wdeprecated-declarations]
        OSSpinLock timer_lock;
        ^
In file included from src/vmm/intel/vmx.c:50:
In file included from include/xhyve/vmm/io/vlapic_priv.h:33:
In file included from /usr/include/libkern/OSAtomic.h:44:
/usr/include/libkern/OSSpinLockDeprecated.h:79:17: note: 'OSSpinLock' has been explicitly marked deprecated here
typedef int32_t OSSpinLock OSSPINLOCK_DEPRECATED_REPLACE_WITH(os_unfair_lock);
                ^
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml/compiler-libs, /usr/local/lib/ocaml
1 error generated.
make[1]: **\* [build/vmm/intel/vmx.o] Error 1
make: **\* [hyperkit] Error 2

Ian de Beer

zenAptix (Pty) Ltd
Octo Place Block B, Unit B01,
Electron Rd,
Technopark.
Stellenbosch, 
South Africa

Mobile: +27 82 887 0926
web: http://www.zenaptix.com

This e-mail transmission contains confidential information, which is the property of EOH Holdings Limited and its subsidiaries (“EOH”). No person, other than the recipient (so indicated by the sender) may use or disclose the contents of this message, links or attachments hereto, to any person whatsoever. Unauthorised disclosure and/or use may result in civil and criminal liability.

Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorised to state them to be the views of any such entity.

The disclaimer forms part of the content of this e-mail in terms of section 11 of the Electronic Communications and Transactions Act, 25 of 2002. Refer to http://www.eoh.co.za/disclaimer

**Comment by AntonioMeireles** [comment]
`brew update && brew rm corectl && brew install corectl --HEAD` should do you the trick.

fwiw - i have no idea about overall state of homebrew in 10.12 betas right now

**Comment by ghost** [comment]
Hi 
The build has gone through - for some reason I don't not get the latest coreOS alpha when corectl tries to update it:

Updating /Users/ian/Library/Caches/Homebrew/corectl--git
==> Checking out branch golang
==> opam init --no-setup
==> opam pin add qcow-format https://github.com/mirage/ocaml-qcow.git#master
==> opam install uri qcow-format ocamlfind
==> make tarball
==> Caveats
Starting with 0.7 "corectl" has a client/server architecture. So before you
can use the "corectl" cli, you have to start the server daemon:

$ corectld start

==> Summary
🍺  /usr/local/Cellar/corectl/HEAD-9a258b8: 29 files, 59.6M, built in 4 minutes 4 seconds
ian:aqueduct_sdk/ (development✗) $ corectld start                                                                                                                                [16:45:36]
Started corectld:
 Version:   0.7.7
 Go Version:    go1.6.2
 Built:     Tue Jul 12 10:59:01 WEST 2016
 OS/Arch:   darwin/amd64

 Pid:       74805
 Uptime:    3 seconds ago

ian:aqueduct_sdk/ (development✗) $ corectl start                                                                                                                                 [16:46:04]
---> downloading and verifying alpha/1122.0.0
50.02 KB / 32.64 MB [>--------------------------------------------------------------------------------------------------------------------------------------------------------] 0.15 % 2m14

Ian de Beer

zenAptix (Pty) Ltd
Octo Place Block B, Unit B01,
Electron Rd,
Technopark.
Stellenbosch, 
South Africa

Mobile: +27 82 887 0926
web: http://www.zenaptix.com

This e-mail transmission contains confidential information, which is the property of EOH Holdings Limited and its subsidiaries (“EOH”). No person, other than the recipient (so indicated by the sender) may use or disclose the contents of this message, links or attachments hereto, to any person whatsoever. Unauthorised disclosure and/or use may result in civil and criminal liability.

Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorised to state them to be the views of any such entity.

The disclaimer forms part of the content of this e-mail in terms of section 11 of the Electronic Communications and Transactions Act, 25 of 2002. Refer to http://www.eoh.co.za/disclaimer

**Comment by AntonioMeireles** [comment]
so `corectl pull` fails for you ?

**Comment by ghost** [comment]
Yes - it starts downloading and then just stops - I have tried multiple times. Do you have a Gitter channel?

Ian de Beer

zenAptix (Pty) Ltd
Octo Place Block B, Unit B01,
Electron Rd,
Technopark.
Stellenbosch, 
South Africa

Mobile: +27 82 887 0926
web: http://www.zenaptix.com

This e-mail transmission contains confidential information, which is the property of EOH Holdings Limited and its subsidiaries (“EOH”). No person, other than the recipient (so indicated by the sender) may use or disclose the contents of this message, links or attachments hereto, to any person whatsoever. Unauthorised disclosure and/or use may result in civil and criminal liability.

Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorised to state them to be the views of any such entity.

The disclaimer forms part of the content of this e-mail in terms of section 11 of the Electronic Communications and Transactions Act, 25 of 2002. Refer to http://www.eoh.co.za/disclaimer

**Comment by AntonioMeireles** [comment]
ping me on kubernetes slack

**Comment by AntonioMeireles** [comment]
there isn't much i can do anyway - looks like golang's crypto in 10.12 a work in progress - either that or plain network issue from your end.

**Comment by ghost** [comment]
Thanks for the help and patience - this is what you get when you install beta software :)
Regards
Ian

Ian de Beer

zenAptix (Pty) Ltd
Octo Place Block B, Unit B01,
Electron Rd,
Technopark.
Stellenbosch, 
South Africa

Mobile: +27 82 887 0926
web: http://www.zenaptix.com

This e-mail transmission contains confidential information, which is the property of EOH Holdings Limited and its subsidiaries (“EOH”). No person, other than the recipient (so indicated by the sender) may use or disclose the contents of this message, links or attachments hereto, to any person whatsoever. Unauthorised disclosure and/or use may result in civil and criminal liability.

Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorised to state them to be the views of any such entity.

The disclaimer forms part of the content of this e-mail in terms of section 11 of the Electronic Communications and Transactions Act, 25 of 2002. Refer to http://www.eoh.co.za/disclaimer

**Comment by AntonioMeireles** [comment]
thanks us! you're welcome!

**Comment by AntonioMeireles** [comment]
afaict there are no remaining issues specific to Sierra for a while, so closing. If you feel this is not true please reopen.
